//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodMap.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public Nullable<int> PrimaryAddress { get; set; }
        public Nullable<int> SecondaryAddress { get; set; }
        public Nullable<int> L_BloodGroupId { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public Nullable<int> NoOfDonation { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual L_BloodGroup L_BloodGroup { get; set; }
        public virtual User User { get; set; }
    }
}
