//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodMap.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Handshake
    {
        public System.Guid Id { get; set; }
        public string SeriesIdentifier { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
